export default [
    {
        key: "client",
        label: "Cliente",
        model: null,
        options: [
            { id: 1, label: "Cliente 1" },
            { id: 2, label: "Cliente 2" },
            { id: 3, label: "Cliente 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
    },
    {
        key: "type_product",
        label: "Tipo de producto",
        model: null,
        options: [
            { id: 1, label: "Tipo 1" },
            { id: 2, label: "Tipo 2" },
            { id: 3, label: "Tipo 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
        multiple: true,
    },
    {
        key: "category",
        label: "Categoria",
        model: null,
        options: [
            { id: 1, label: "Categoria 1" },
            { id: 2, label: "Categoria 2" },
            { id: 3, label: "Categoria 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
    },
    {
        key: "brand",
        label: "Marca",
        model: null,
        options: [
            { id: 1, label: "Marca 1" },
            { id: 2, label: "Marca 2" },
            { id: 3, label: "Marca 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
    },
    {
        key: "model",
        label: "Modelo",
        model: null,
        options: [
            { id: 1, label: "Modelo 1" },
            { id: 2, label: "Modelo 2" },
            { id: 3, label: "Modelo 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
    },
    {
        key: "color",
        label: "Color",
        model: null,
        options: [
            { id: 1, label: "Color 1" },
            { id: 2, label: "Color 2" },
            { id: 3, label: "Color 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
    },
    {
        key: "size",
        label: "Tamaño",
        model: null,
        options: [
            { id: 1, label: "Tamaño 1" },
            { id: 2, label: "Tamaño 2" },
            { id: 3, label: "Tamaño 3" },
        ],
        visible: true,
        clearable: true,
        cols: 12,
        md: 12,
    },
];

