export default [
    {
        key: "name",
        label: "Producto",
        sortable: true,
        visible: true,
    },
    {
        key: "unit_price",
        label: "Precio unitario (S/.)",
        sortable: true,
        visible: true,
        tdClass: "text-center",
        thClass: "text-center",
    },
    {
        key: "stock",
        label: "Stock actual",
        sortable: true,
        visible: true,
        tdClass: "text-center",
        thClass: "text-center",
    },
    {
        key: "supplier_name",
        label: "Proveedor",
        sortable: false,
        visible: true,
    },
    {
        key: "created_at",
        label: "Creado el",
        sortable: true,
        visible: true,
        tdClass: "text-center",
        thClass: "text-center",
    },
    {
        key: "actions",
        label: "Acciones",
        sortable: false,
        visible: true,
        tdClass: "text-center",
        thClass: "text-center",
    },
];
